name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest  # Cambia a ubuntu-latest si prefieres Linux

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Clonación completa para mejor análisis

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Cambia si usas otra versión

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
