name: Tests con conexión a Base de Datos

on:
  push:
    branches: [development]
  pull_request:
    branches: [development]

jobs:
  test-db-connection:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Esperar a que Postgres esté listo
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 && break
            echo "Esperando por Postgres... ($i)"
            sleep 1
          done

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependencias
        run: npm install

      - name: Crear archivo .env para pruebas
        run: |
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=postgres" >> .env
          echo "DB_NAME=test_db" >> .env

      - name: Ejecutar pruebas con cobertura
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_NAME: test_db
        run: npm test -- --coverage
